export { Header } from './Header'
export { Footer } from './Footer'
export { Promo } from './Promo'
export { About } from './About'
export { Contact } from './Contact'
export { Privacy } from './Privacy'
